---
- name: 'network Ping Test'
  ping:
  register: result
  
- name: 'Result check'
  debug:
    msg: '{{ result }}'

- name: 'huawei facts check'
  ce_facts:
  register: facts_check

- name: 'debug'
  debug:
    msg: '{{ facts_check }}'
