---
- name: '< Database > Setting my.cnf [ server_id ]'
  lineinfile:
    path: '/etc/my.cnf'
    regexp: 'server_id=101'
    line: 'server_id=102'
  when: inventory_hostname == vm_ipaddr_6
  register: db_result

- name: '< Database > Result Check'
  debug:
    msg: '{{ db_result }}'
  when: inventory_hostname == vm_ipaddr_6

- name: '< Database > Setting Heartbeat IP Address Database [ {{ vm_hostname }} ]'
  set_fact:
    vm_array_1: '{{ vm_ipaddr_5.split(".") }}'
  when: inventory_hostname == vm_ipaddr_5

- name: '< Database > Setting Variable Heartbeat IP Address [ {{ vm_hostname }} ]'
  set_fact:
    vm_heartbeat_ip_1: '192.168.100.{{ vm_array_1[3] }}'
  when: inventory_hostname == vm_ipaddr_5

- name: '< Database > Setting Heartbeat IP Address [ {{ vm_hostname }} ]'
  shell: 'nmcli con add con-name ens256 ifname ens256 type ethernet ip4 {{ vm_heartbeat_ip_1 }}/24 ipv4.method manual autoconnect yes'
  register: heartbeat_result1
  when: inventory_hostname == vm_ipaddr_5

- name: '< Database > Result Check'
  debug:
    msg: '{{ heartbeat_result1 }}'
  when: inventory_hostname == vm_ipaddr_5
    
- name: '< Database > Setting Heartbeat IP Address Database [ {{ vm_hostname }} ]'
  set_fact:
    vm_array_2: '{{ vm_ipaddr_6.split(".") }}'
  when: inventory_hostname == vm_ipaddr_6

- name: '< Database > Setting Heartbeat IP Address [ {{ vm_hostname }} ]'
  set_fact:
    vm_heartbeat_ip_2: '192.168.100.{{ vm_array_2[3] }}'
  when: inventory_hostname == vm_ipaddr_6

- name: '< Database > Setting Heartbeat IP Address [ {{ vm_hostname }} ]'
  shell: 'nmcli con add con-name ens256 ifname ens256 type ethernet ip4 {{ vm_heartbeat_ip_2 }}/24 ipv4.method manual autoconnect yes'
  register: heartbeat_result2
  when: inventory_hostname == vm_ipaddr_6

- name: '< Database > Result Check'
  debug:
    msg: '{{ heartbeat_result2 }}'
  when: inventory_hostname == vm_ipaddr_6
