---
- name: '< MAIN : WEB > [ {{ vm_purpose }} ] Launch Create VM Web Service Template'
  include_tasks: web_template.yml
  when: vm_web_ck == 'yes'

- name: '< MAIN : WAS > [ {{ vm_purpose }} ] Launch Create VM WAS Service Template'
  include_tasks: was_template.yml

- name: '< MAIN : Database > [ {{ vm_purpose }} ] Launch Create VM Database Service Template [ DB Type is {{ vm_db_type }} ]'
  include_tasks: database_template.yml
