---
rs_hostname: ""
rs_os_family: ""
rs_os_version: ""
rs_ip_addr: ""
rs_cpu_used: ""
rs_cpu_msg: ""
rs_mem_used: ""
rs_mem_msg: ""
rs_disk_used: ""
rs_disk_msg: ""
rs_inode_used: ""
rs_inode_msg: ""
rs_ntp_set: ""
rs_ntp_run: ""
rs_svc_running: ""
rs_svc2_running: ""
