---
- name: '< Condition : Apache -01 > Get Apache Service [ Apache proxy, Web ]'
  shell: 'ps -eo comm,etime,user | grep httpd'
  register: get_apache
  ignore_errors: true

- name: '< Condition : Apache > Set Result'
  set_fact:
    rs_svc_running: '{{ "Apache : Running" if( get_apache.rc == 0 ) else "Apache : Not Running" }}'
