---
- name: '< Apache -01 >  Get Apache Service [ Apache proxy, Web ]'
  shell: 'ps -eo comm,etime,user | grep httpd'
  register: get_apache
  ignore_erros: true

- name: '< Apache -01 >  Set Apache Service is Running [ Apache proxy, Web ]'
  set_fact:
    rs_svc_running: 'Apache : Running'
  when: get_apache.rc == 0
  
- name: '< Apache -01 >  Set Apache Service is Not Running [ Apache proxy, Web ]'
  set_fact:
    rs_svc_running: 'Apache : Not Running'
  when: get_apache.rc != 0
