---
- name: '< Haproxy Condition Check -01 > Check Haproxy Service'
  systemd:
    name: haproxyd
  register: get_haproxy

- name: debug
  debug:
    var: get_haproxy.status.ActiveState
    
- name: '< Haproxy Condition Check -02 > Check keepalived Service'
  systemd:
    name: keepalived
  register: get_keepalived

- name: debug
  debug:
    var: get_keepalived.status.ActiveState
