---
- name: '< Main > Get Date'
  shell: 'echo $(date +"%Y%m%d%S")'
  register: get_date
  delegate_to: localhost
  run_once: yes

- name: '< Main > Get Hostname'
  shell: 'hostname'
  register: get_hostname

- name: '< Main > Set Hostname'
  set_fact:
    rs_hostname: '{{ get_hostname.stdout }}'
    
- name: '< Main > Common OS Condition check'
  include_tasks: common_condition_check.yml

- name: '< Main > Apache Service Condition check [ Apache Proxy, WEB ]'
  include_tasks: apache_condition_check.yml
  when: rs_hostname[5:8]|lower == 'pxy' or rs_hostname[5:8]|lower == 'web'

- name: '< Main > WAS Service Condition check [ WAS ]'
  include_tasks: was_condition_check.yml
  when: rs_hostname[5:8]|lower == 'was'

- name: '< Main > Database Service Condition check [ MariaDB, Mysql ]'
  include_tasks: database_condition_check.yml
  when: rs_hostname[5:8]|lower == 'mas' or rs_hostname[5:8]|lower == 'mys'

- name: '< Main > Haproxy Service Condition check'
  include_tasks: haproxy_condition_check.yml
  when: rs_hostname[5:8]|lower == 'pxy'

- name: 'main task debug'
  debug:
    msg: '{{ rs_hostname }} | {{ rs_os_family }} | {{ rs_os_version }} | {{ rs_cpu_msg }} | {{ rs_mem_msg }} | {{ rs_disk_msg }} | {{ rs_disk_used }} | {{ rs_inode_msg }} | {{ rs_inode_used }} | {{ rs_ntp_set }} | {{ rs_ntp_run }} | {{ rs_svc_running }}'

- name: 'create result file'
  file:
    path: '/var/lib/awx/projects/result/{{ get_date.stdout }}_condition_result'
    state: touch
  delegate_to: localhost
  run_once: yes

- name: 'result file add'
  lineinfile:
    path: '/var/lib/awx/projects/result/{{ get_date.stdout }}_condition_result'
    line: '{{ rs_hostname }} | {{ rs_os_family }} | {{ rs_os_version }} | {{ rs_cpu_msg }} | {{ rs_mem_msg }} | {{ rs_disk_msg }} | {{ rs_disk_used }} | {{ rs_inode_msg }} | {{ rs_inode_used }} | {{ rs_ntp_set }} | {{ rs_ntp_run }} | {{ rs_svc_running }}'
  delegate_to: localhost
