---
- name: '< Main > Get Date'
  shell: 'echo $(date +"%Y%m%d%H%M%S")'
  register: get_date
  delegate_to: localhost
  run_once: yes

- name: '< Main > Get Hostname'
  shell: 'hostname'
  register: get_hostname

- name: '< Main > Set Hostname'
  set_fact:
    rs_hostname: '{{ get_hostname.stdout }}'
    
- name: '< Main > Common OS Condition check'
  include_tasks: common_condition_check.yml

- name: '< Main > Apache Service Condition check [ Apache Proxy, WEB ]'
  include_tasks: apache_condition_check.yml
  when: rs_hostname[5:8]|lower == 'pxy' or rs_hostname[5:8]|lower == 'web'

- name: '< Main > WAS Service Condition check [ WAS ]'
  include_tasks: was_condition_check.yml
  when: rs_hostname[5:8]|lower == 'was'

- name: '< Main > Database Service Condition check [ MariaDB, Mysql ]'
  include_tasks: database_condition_check.yml
  when: rs_hostname[5:8]|lower == 'mas' or rs_hostname[5:8]|lower == 'mys' or rs_hostname[5:8]|lower == 'mha'

- name: '< Main > Haproxy Service Condition check'
  include_tasks: haproxy_condition_check.yml
  when: rs_hostname[5:8]|lower == 'pxy'

- name: 'main task debug'
  debug:
    msg: '{{ rs_hostname }} | {{ rs_os_family }} | {{ rs_os_version }} | {{ rs_ip_addr }} | {{ rs_cpu_msg }} | {{ rs_mem_msg }} | {{ rs_disk_msg }} | {{ rs_disk_used }} | {{ rs_inode_msg }} | {{ rs_inode_used }} | {{ rs_ntp_set }} | {{ rs_ntp_run }} | {{ rs_svc_running }}'

- name: 'create result file'
  file:
    path: '/var/lib/awx/projects/result/{{ get_date.stdout }}_condition_result.csv'
    state: touch
  delegate_to: localhost
  run_once: yes

- name: 'result file add title'
  lineinfile:
    path: '/var/lib/awx/projects/result/{{ get_date.stdout }}_condition_result.csv'
    line: 'Hostname, OS Type, OS Version, IP Address, CPU 사용량, Memory 사용량, Disk 상태, Disk 사용량, i-node 상태, i-node 사용량, NTP설정, Chrony 상태, Service 1 상태, Service 2 상태'
  delegate_to: localhost
  run_once: yes


- name: 'result file add'
  lineinfile:
    path: '/var/lib/awx/projects/result/{{ get_date.stdout }}_condition_result.csv'
    line: '"{{ rs_hostname }}","{{ rs_os_family }}","{{ rs_os_version }}","{{ rs_ip_addr }}","{{ rs_cpu_msg }}","{{ rs_mem_msg }}","{{ rs_disk_msg }}","{{ rs_disk_used }}","{{ rs_inode_msg }}","{{ rs_inode_used }}","{{ rs_ntp_set }}","{{ rs_ntp_run }}","{{ rs_svc_running }}","{{ rs_svc2_running }}"'
  delegate_to: localhost
