---
- name: '< Main > Get Hostname'
  shell: 'hostname'
  register: get_hostname

- name: '< Main > Set Hostname'
  set_fact:
    rs_hostname: '{{ get_hostname.stdout }}'
    
- name: '< Main > Common OS Condition check'
  include_tasks: common_condition_check.yml

- name: '< Main > Apache Service Condition check [ Apache Proxy, WEB ]'
  include_tasks: apache_condition_check.yml
  when: rs_hostname[5:8]|lower == 'pxy' or rs_hostname[5:8]|lower == 'web'

- name: '< Main > WAS Service Condition check [ WAS ]'
  include_tasks: was_condition_check.yml
  when: rs_hostname[5:8]|lower == 'was'

#- name: '< Main > Database Service Condition check [ MariaDB, Mysql ]'
#  include_tasks: database_condition_check.yml
#  when: rs_hostname[5:8]|lower == 'mas' or rs_hostname[5:8]|lower == 'mys'

- name: '< Main > Haproxy Service Condition check'
  include_tasks: haproxy_condition_check.yml
  when: rs_hostname[5:8]|lower == 'pxy'
