---
- name: 'Common OS Condition check'
  include_tasks: common_condition_check.yml

#- name: 'Apache Service Condition check [ Apache Proxy, Web ]'
#  include_tasks: apache_condition_check.yml
#  when: ansible_hostname[5:8]|lower == 'pxy' or ansible_hostname[5:8]|lower == 'webaaa'

#- name: 'Was Service Condition check [ Was ]'
#  include_tasks: was_condition_check.yml
#  when: ansible_hostname[5:8]|lower == 'was'

#- name: 'Database Service Condition check [ MariaDB, Mysql ]'
#  include_tasks: database_condition_check.yml
#  when: ansible_hostname[5:8]|lower == 'mas' or ansible_hostname[5:8]|lower == 'mys'

- name: 'Haproxy Service Condition check'
  include_tasks: haproxy_condition_check.yml
  when: ansible_hostname[5:8]|lower == 'pxy'
