---
# WAS -01 : Tomcat 서비스 상태 확인
- name: '< Condition : WAS -01 > Get Was Service'
  shell: 'ps -ef | grep tomcat | grep Bootstrap'
  register: get_was

# 상기 수집된 정보를 CSV File로 출력하기 위해 전역 변수에 저장.
# 수집 결과 저장시 이상 유무 조건을 체크하여 저장 처리
- name: '< Condition : WAS > Set Result'
  set_fact:
    rs_svc_running: '{{ "Tomcat : Running" if( get_was.stdout is search("startup") ) else "Tomcat : Not Running" }}'
