---
- name: '< WAS -01 > Get Was Service'
  shell: 'ps -ef | grep tomcat | grep Bootstrap'
  register: get_was

#- name: '< WAS -01 > Set Was Service Process Running '
#  set_fact:
#    rs_svc_running: 'Tomcat : Running'
#  when: get_was.stdout|search('startup') != ""

#- name: '< WAS -01 > Set Was Service Process Not Running'
#  set_fact:
#    rs_svc_running: 'Tomcat : Not Running'
#  when: get_was.stdout|search('startup') == ""


- name: fact check
  shell: echo "{{ get_was.stdout_lines|select('match','startup') }}"
  register: find_startup
- debug:
    var: find_startup
- name: '< WAS -01 > Set Was Service Process Running '
  set_fact:
    rs_svc_running: 'Tomcat : Running'
  when: find_startup.matched > 0
  
#- name: '< WAS -01 > Set Was Service Process Not Running'
#  set_fact:
#    rs_svc_running: 'Tomcat : Not Running'
#  when: get_was.stdout_lines|select('match','startup') == ""


