---
# Survey를 통해 입력받은 IP 주소를 vm_iparray List에 등록
- name: '< Check Ping -01 > Set list of IP Addresses'
  set_fact:
    vm_ip_list: '{{ vm_ip_list | default([]) + [ item ] }}'
  with_items:
    - { 'ip_addr':'{{ vm_ipaddr_1 }}' }
    - { 'ip_addr':'{{ vm_ipaddr_2 }}' }
    - { 'ip_addr':'{{ vm_ipaddr_3 }}' }
    - { 'ip_addr':'{{ vm_ipaddr_4 }}' }
    - { 'ip_addr':'{{ vm_ipaddr_5 }}' }
    - { 'ip_addr':'{{ vm_ipaddr_6 }}' }
    - { 'ip_addr':'{{ vm_ipaddr_7 }}' }
    - { 'ip_addr':'{{ vm_ipaddr_8 }}' }
    - { 'ip_addr':'{{ vm_ipaddr_9 }}' }
    - { 'ip_addr':'{{ vm_proxy_vip }}' }
    - { 'ip_addr':'{{ vm_db_vip }}' }

# vm_iparray에 등록된 IP주소로 Ping Test 수행
- name: '< Check Ping -02 > Check IP addresses Ping'
  shell: 'ping {{ item.ip_addr }} -c 3'
  register: rs_ping
  delegate_to: localhost
  loop: '{{ vm_ip_list }}'
  when: item.ip_addr != none
  ignore_errors: true

# Ping Tes 결과값을 통해 사용중인 IP 주소를 등록
# > 사용중인 IP 구분 기준
#     - 응답, 응답지연의 경우 사용중인 IP로 인지
#     - 100% packet loss가 아닐 경우 사용중인 IP로 인지
- name: '< Check Ping -03 > Extract list of live IP addresses'
  set_fact:
    live_ip_list: '{{ live_ip_list | default([]) + [ item.item.ip_addr ] }}'
  loop: '{{ rs_ping.results }}'
  when: item.changed == true and item.stdout is not search('100% packet loss')

# Ping Test를 통한 IP 주소 사용여부 확인 안내 메세지
# > 사용중인 IP 목록 변수(=live_ip_list)에 값이 있으면 강제 Failed 처리
- name: '< Check Ping -04 > Results of checking the IP address in use'
  debug:
    msg: '{% if live_ip_list|length > 0 %}다음의 IP 주소들이 사용중인 것으로 확인됩니다. {{ live_ip_list | replace("u","") }}
          {% else %} 사용중인 IP 주소가 없는 것으로 확인됩니다. {% endif %}'
  failed_when: live_ip_list|length > 0
