---
- name: '< MAIN : Setting > Set Global Variables'
  include_tasks: setting_variables.yml

- name: '< MAIN : Login > Kubevirt Login'
  shell: 'oc login {{ kvrt_account | b64decode }} --server=https://api.{{ var_cluster }}.lguplus.co.kr:6443 --insecure-skip-tls-verify=true'
  register: result_01

- name: '< MAIN : Login > Debug'
  debug:
    msg: '{{ result_01 }}'
  
- name: '< MAIN : Create VM > [ {{ var_purpose | upper }} ] Launch create VM Template'
  include_tasks: use_template.yml
  loop: '{{ var_vminfo }}'

- name: '< MAIN : Waiting > Wait 70 Seconds for new virtual machine to booting'
  pause:
    seconds: 70

- name: '< MAIN : Check VM > Check the created virtual machine'
  shell: 'oc get pvc,vmi -n {{ var_namespace | lower}} | grep "{{ var_namespace | lower }}"'
  register: result_04

- name: '< Create VM -03- > Debug'
  debug:
    msg: '{{ result_04.stdout_lines }}'

- name: '< MAIN : Logout > Kubevirt Logout'
  shell: 'oc logout'
