---
vm_purpose: ''
vm_type: ''
vm_code: ''
vm_count: ''
vm_ipaddr_1: ''
kvrt_login: 'b2MgbG9naW4gLXUgYWRtaW4gLXAgZGplbWFsczEhIC0tc2VydmVyPWh0dHBzOi8vYXBpLmRrdnJ0LWs4cy5sZ3VwbHVzLmNvLmtyOjY0NDMgLS1pbnNlY3VyZS1za2lwLXRscy12ZXJpZnk9dHJ1ZQ=='
