---
- name: "< Haproxy {{ proxy_type|upper }} Setting - 01 > {{ proxy_type|upper }} Config Template Copy"
  shell: "cp /engn/haproxy/conf/haproxy.{{ proxy_type|lower }}.cfg /engn/haproxy/conf/haproxy.cfg"
  register: result_01

- name: "< Haproxy {{ proxy_type|upper }} Setting - 01 > Result Check"
  debug:
    msg: "{{ result_01 }}"
    
- name: "< Haproxy {{ proxy_type|upper }} Setting - 02 > {{ proxy_type|upper }} Config Bind Port"
  lineinfile:
    path: "/engn/haproxy/conf/haproxy.cfg"
    regexp: "   bind :8888"
    line: "   bind :{{ bind_port }}"
  register: result_02

- name: "< Haproxy {{ proxy_type|upper }} Setting - 02 > Result Check"
  debug:
    msg: "{{ result_02 }}"
    
- name: "< Haproxy {{ proxy_type|upper }} Setting - 03 > Initialize the {{ proxy_type|upper }} Server member"
  lineinfile:
    path: "/engn/haproxy/conf/haproxy.cfg"
    regexp: "{{ item }}"
    state: absent
  register: result_03
  loop:
    - "server s1 192.168.1.25:8888 check fall 5 inter 2000 rise 2"
    - "server s2 192.168.1.26:8888 check fall 5 inter 2000 rise 2"

- name: "< Haproxy {{ proxy_type|upper }} Setting - 03 > Result Check"
  debug:
    msg: "{{ result_03 }}"
    
- name: "< Haproxy {{ proxy_type|upper }} Setting - 04 > Add {{ proxy_type|upper }} server member"
  lineinfile:
    path: "/engn/haproxy/conf/haproxy.cfg"
    insertafter: "balance roundrobin"
    line: "{{ item }}"
  register: result_04
  loop:
    - "   server s2 {{ vm_member_2 }} check fall 5 inter 2000 rise 2"
    - "   server s1 {{ vm_member_1 }} check fall 5 inter 2000 rise 2"

- name: "< Haproxy {{ proxy_type|upper }} Setting - 04 > Result Check"
  debug:
    msg: "{{ result_04 }}"
