---
- name: '< Application Running > Apache Service [ Apache_proxy, Web ]'
  include_tasks: apache_running.yml
  when: vm_type|lower == 'pxy' or vm_type|lower == 'web'

- name: '< Application Running > HaProxy Service'
  include_tasks: haproxy_running.yml
  when: vm_type|lower == 'hpxy'

- name: '< Application Running > Was Service'
  include_tasks: was_running.yml
  when: vm_type|lower == 'was'
