---
- name: '< Was > Service Running instance11 [ cmd : /engn/tomcat/servers/instance11/start-instance11.sh ]'
  shell: '/engn/tomcat/servers/instance11/start-instance11.sh'
  register: running_state
  when: inventory_hostname == vm_ipaddr_1

- name: '< Was > Running State Check'
  debug:
    msg: '{{ running_state }}'
  when: inventory_hostname == vm_ipaddr_1

- name: '< Was > Service Running instance21 [ cmd : /engn/tomcat/servers/instance21/start-instance21.sh ]'
  shell: '/engn/tomcat/servers/instance11/start-instance21.sh'
  register: running_state
  when: inventory_hostname == vm_ipaddr_2

- name: '< Was > Running State Check'
  debug:
    msg: '{{ running_state }}'
  when: inventory_hostname == vm_ipaddr_2
