- name: change power state the VM after 1 minutes
  include_tasks: poweroff_after_pause.yml
  when: running_check == "yes"

- name: Check variable input values to control VM power
  debug:
    msg: "You must enter yes to control the power of the VM. the value you entered : {{ running_check }}"
  when: running_check != "yes"
