---
- name: '< MAIN : Application > [ {{ vm_purpose|upper }} ] Launch Create VM Applicaton Template [ VM Type is WEB, WAS ]'
  include_tasks: application_template.yml
  when: vm_type|lower == 'web' or vm_type|lower == 'was'

- name: '< MAIN : Haproxy > [ {{ vm_purpose|upper }} ] Launch Create VM Haproxy Template'
  include_tasks: haproxy_template.yml
  when: vm_type|lower == 'pxy'

- name: '< MAIN : Database > [ {{ vm_purpose|upper }} ] Launch Create VM Database Template [ DB Type is {{ vm_type|upper }} ]'
  include_tasks: database_template.yml
  when: vm_type|lower == 'mas' or vm_type|lower == 'mys'

- name: '< MAIN : Database > [ {{ vm_purpose|upper }} ] Launch Create VM MHA Template [ DB Type is {{ vm_type|upper }} ]'
  include_tasks: mha_template.yml
  when: ( vm_type|lower == 'mas' and vm_ipaddr_3 != None ) or ( vm_type|lower == 'mys' and vm_ipaddr_3 != None )

- name: '< MAIN : Other > [ {{ vm_purpose|upper }} ] Launch Create VM Other Template'
  include_tasks: other_template.yml
  when: vm_type|lower != 'pxy' and vm_type|lower != 'web' and vm_type|lower != 'was' and vm_type|lower != 'mas' and vm_type|lower != 'mys'
