---
- name: "< Application Config - 01 > [ VM Type: WEB, PXY, WAS ] Create User {{ vm_name[1:5]|lower }}adm & {{ vm_name[1:5]|lower }}usr"
  user:
    name: "{{ item.user }}"
    uid: "{{ item.uid }}"
    group: "3000"
    password: "{{ 'dlatl00' | password_hash('sha512') }}"
  register: app_rs_01
  loop:
    - { user: "{{ vm_name[1:5]|lower }}adm", uid: "3100" }
    - { user: "{{ vm_name[1:5]|lower }}usr", uid: "3200" }

- name: "< Application Config - 01 > [ VM Type: WEB, PXY, WAS ] Result Check"
  debug:
    msg: "{{ app_rs_01 }}"

- name: "< Application Config - 02 > [ VM Type: WEB, PXY, WAS ] Add sudo privileges to the {{ vm_name[1:5]|lower }}adm User"
  copy:
    content: "{{ vm_name[1:5]|lower }}adm ALL=(ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ vm_name[1:5]|lower }}adm"
  register: app_rs_02

- name: "< Application Config - 02 > [ VM Type: WEB, PXY, WAS ] Result Check"
  debug:
    msg: "{{ app_rs_02 }}"

- name: "< Application Config - 03-1 > [ VM Type: WEB, PXY ] Set Directory Permissions"
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: "{{ item.user }}"
    group: "3000"
  register: app_rs_03-1
  loop:
    - { dir: "/engn/apache", user: "{{ vm_name[1:5]|lower }}adm" }
    - { dir: "/sorc/webdocs", user: "{{ vm_name[1:5]|lower }}usr" }
    - { dir: "/logs/apache", user: "{{ vm_name[1:5]|lower }}adm" }
  when: vm_name[5:8]|lower == "web" or vm_name[5:8]|lower == "pxy"

- name: "< Application Config - 03-1 > [ VM Type: WEB, PXY ] Result Check"
  debug:
    msg: "{{ app_rs_03-1 }}"
  when: vm_name[5:8]|lower == "web" or vm_name[5:8]|lower == "pxy"

- name: "< Application Config - 03-2 > [ VM Type: WAS ] Set Directory Permissions"
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: "{{ item.user }}"
    group: "3000"
  register: app_rs_03-2
  loop:
    - { dir: "/engn/tomcat", user: "{{ vm_name[1:5]|lower }}adm" }
    - { dir: "/sorc/applications", user: "{{ vm_name[1:5]|lower }}usr" }
    - { dir: "/logs/tomcat", user: "{{ vm_name[1:5]|lower }}adm" }
  when: vm_name[5:8]|lower == "was"

- name: "< Application Config - 03-2 > [ VM Type: WAS ] Result Check"
  debug:
    msg: "{{ app_rs_03-2 }}"
  when: vm_name[5:8]|lower == "was"  
