---
- name: "Common Config Setting"
  include_tasks: common_config.yml

- name: "Application Config Setting"
  include_tasks: application_config.yml
  when: vm_type|lower == 'pxy' or vm_type|lower == 'web' or vm_type|lower == 'was'

- name: "WEB Server HA Config Setting"
  include_tasks: web_config.yml
  when: vm_type|lower == 'web' and vm_purpose|lower == 'prd'
