---
- name: '< Application : WAS > Setting instance11 server.xml'
  lineinfile:
    path: '/engn/tomcat/servers/instance11/conf/server.xml'
    regexp: '{{ item.origin }}'
    line: '{{ item.change }}'
  loop: 
    - { 'origin':'address="172."', 'change':'address="{{ vm_ipaddr_1 }}"' }
    - { 'origin':'host="172."', 'change':'host="{{ vm_ipaddr_2 }}"' }
  when: inventory_hostname == vm_ipaddr_1
  register: ins11_server_1

- name: '< Application : WAS > Result Check'
  debug:
    msg: '{{ ins11_server_1 }}'
