---
- name: '< Application : WAS > Setting instance11 server.xml'
  lineinfile:
    path: '/engn/tomcat/servers/instance11/conf/server.xml'
    regexp: '{{ item.origin }}'
    line: '{{ item.change }}'
  loop: 
    - { 'origin':'address="172."', 'change':'                     address="{{ vm_ipaddr_1 }}"' }
    - { 'origin':'host="172."', 'change':'                     host="{{ vm_ipaddr_2 }}"' }
  when: inventory_hostname == vm_ipaddr_1
  register: ins11_result

- name: '< Application : WAS > Result Check'
  debug:
    msg: '{{ ins11_result }}'
  when: inventory_hostname == vm_ipaddr_1

- name: '< Application : WAS > Rename instance11 to instance21 server.xml'
  shell: '{{ item }}'
  loop: 
    - 'mv /engn/tomcat/servers/instance11 /engn/tomcat/servers/instance21'
    - 'mv /logs/tomcat/instance11 /logs/tomcat/instance21'
    - 'mv /sorc/applications/instance11 /sorc/applications/instance21'
  when: inventory_hostname == vm_ipaddr_2
  register: ins21_rename

- name: '< Application : WAS > Result Check'
  debug:
    msg: '{{ ins21_rename }}'
  when: inventory_hostname == vm_ipaddr_2

- name: '< Application : WAS > Remove Symbolic link Directory Logs/instance11'
  file:
    path: '/engn/tomcat/servers/instance21/logs'
    state: absent
  when: inventory_hostname == vm_ipaddr_2
  register: ins21_remove

- name: '< Application : WAS > Result Check'
  debug:
    msg: '{{ ins21_remove }}'
  when: inventory_hostname == vm_ipaddr_2

- name: '< Application : WAS > Create Symbolic link Directory Logs/instance21'
  file:
    src: '/logs/tomcat/instance21'
    dest: '/engn/tomcat/servers/instance21/logs'
    owner: '3100'
    group: '3000'
    state: link
  when: inventory_hostname == vm_ipaddr_2
  register: ins21_symbol

- name: '< Application : WAS > Result Check'
  debug:
    msg: '{{ ins21_symbol }}'
  when: inventory_hostname == vm_ipaddr_2

- name: '< Application : WAS > Setting instance21 server.xml'
  lineinfile:
    path: '/engn/tomcat/servers/instance21/conf/server.xml'
    regexp: '{{ item.origin }}'
    line: '{{ item.change }}'
  loop: 
    - { 'origin':'address="172."', 'change':'                     address="{{ vm_ipaddr_2 }}"' }
    - { 'origin':'host="172."', 'change':'                     host="{{ vm_ipaddr_1 }}"' }
  when: inventory_hostname == vm_ipaddr_2
  register: ins21_result

- name: '< Application : WAS > Result Check'
  debug:
    msg: '{{ ins21_result }}'
  when: inventory_hostname == vm_ipaddr_2

- name: '< Application : WAS > Setting instance21 Running Script [ env.sh ]'
  lineinfile:
    path: '/engn/tomcat/servers/instance21/bin/env.sh'
    regexp: 'instance11'
    line: 'instance21'
  when: inventory_hostname == vm_ipaddr_2
  register: ins21_env

- name: '< Application : WAS > Result Check'
  debug:
    msg: '{{ ins21_env }}'
  when: inventory_hostname == vm_ipaddr_2

- name: '< Application : WAS > Setting instance21 Start shell'
  shell: '{{ item }}'
  loop:
    - 'mv /engn/tomcat/servers/instance21/bin/start-instance11.sh /engn/tomcat/servers/instance21/bin/start-instance21.sh'
    - 'mv /engn/tomcat/servers/instance21/bin/stop-instance11.sh /engn/tomcat/servers/instance21/bin/stop-instance21.sh'
  when: inventory_hostname == vm_ipaddr_2
  register: ins21_shell
  
- name: '< Application : WAS > Result Check'
  debug:
    msg: '{{ ins21_shell }}'
  when: inventory_hostname == vm_ipaddr_2
