---
- name: 'Check variable input values to control VM power'
  debug:
    msg: 'You must enter yes to control the power of the VM. the value you entered : {{ running_check }}'
  when: running_check != 'yes'

- name: '[KVRT] Change the power state of the VM'
  include_tasks: power_mgmt.yml
  when: running_check == 'yes'
