---
- name: 'Check variable input values to control VM power'
  debug:
    msg: 'You must enter yes to control the power of the VM. the value you entered : {{ running_check }}'
  when: running_check != 'yes'

- name: 'Kubevirt VM Power On'
  include_tasks: power_on.yml
  when: running_check == 'yes'
