---
- name: '< HA Service Set : DATABASE -01 > Creating a database service virtual machine [ {{ vm_db_type | upper }} ]'
  vmware_guest:
    validate_certs: false
    folder: /IAAS_Datacenter/vm
    datacenter: IAAS_Datacenter
    cluster: 'IAAS_iac(D)_Cluster'
    name: '{{ item }}'
    state: poweredon
    template: 'TMP_RHEL8.6_{{ vm_purpose | upper }}_{{ vm_db_type | upper }}'
    disk:
    - size_gb: 60
      type: thin
      datastore: DIAAS_OS_NAS11
    - size_gb: 370
      type: thin
      datastore: DIAAS_OS_NAS11
    hardware:
      memory_mb: 8192
      num_cpus: 4
      scsi: paravirtual
      mem_reservation: 8192
      cpu_shares_level: "normal"
      mem_shares_level: "normal"
  delegate_to: localhost
  register: rs_create_vm
  loop:
    - '{{ vm_purpose[0:1] | lower }}{{ vm_code | lower }}{{ vm_db_type | lower }}1v'
    - '{{ vm_purpose[0:1] | lower }}{{ vm_code | lower }}{{ vm_db_type | lower }}2v'

- name: '< HA Service Set : DATABASE -01 > Debugging [ {{ vm_db_type | upper }} ]'
  debug:
    msg: '{{ rs_create_vm }}'

- name: '< HA Service Set : DATABASE -02 > Creating a database MHA service virtual machine [ {{ vm_db_type | upper }} ]'
  vmware_guest:
    validate_certs: false
    folder: /IAAS_Datacenter/vm
    datacenter: IAAS_Datacenter
    cluster: 'IAAS_iac(D)_Cluster'
    name: '{{ vm_purpose[0:1] | lower }}{{ vm_code | lower }}mha1v'
    state: poweredon
    template: 'TMP_RHEL8.6_{{ vm_purpose|upper }}_{{ vm_db_type | upper }}_MHA'
    disk:
    - size_gb: 60
      type: thin
      datastore: DIAAS_OS_NAS11
    - size_gb: 370
      type: thin
      datastore: DIAAS_OS_NAS11
    hardware:
      memory_mb: 8192
      num_cpus: 4
      scsi: paravirtual
      mem_reservation: 8192
      cpu_shares_level: "normal"
      mem_shares_level: "normal"
  delegate_to: localhost
  register: rs_create_mha

- name: < HA Service Set : DATABASE -02 > Debugging MHA [ {{ vm_db_type | upper }} ]'
  debug:
    msg: '{{ rs_create_mha }}'

- name: '< HA Service Set : DATABASE -03 >  DATABASE Service virtual machine booting stand by 30 second [ {{ vm_db_type | upper }} ]'
  pause:
    seconds: 30
    
- name: '< HA Service Set : DATABASE -04 > DATABASE service virtual machine IP settings [ {{ vm_db_type | upper }} ]'
  vmware_vm_shell:
    validate_certs: false
    folder: /IAAS_Datacenter/vm
    datacenter: IAAS_Datacenter
    vm_id: '{{ item.hostname }}'
    vm_username: '{{ vm_user }}'
    vm_password: '{{ vm_pw }}'
    vm_shell: "/usr/bin/sudo"
    vm_shell_args: "nmcli con add con-name ens192 ifname ens192 type ethernet ip4 {{ item.ip_addr }}/24 ipv4.method manual autoconnect yes && sudo hostnamectl set-hostname {{ item.hostname }}"
  delegate_to: localhost
  register: rs_ip_set_vm
  loop:
    - { 'hostname':'{{ vm_purpose[0:1] | lower }}{{ vm_code | lower }}{{ vm_db_type | lower }}1v', 'ip_addr':'{{ vm_ipaddr_5 }}' }
    - { 'hostname':'{{ vm_purpose[0:1] | lower }}{{ vm_code | lower }}{{ vm_db_type | lower }}2v', 'ip_addr':'{{ vm_ipaddr_6 }}' }
    - { 'hostname':'{{ vm_purpose[0:1] | lower }}{{ vm_code | lower }}mha1v', 'ip_addr':'{{ vm_ipaddr_7 }}' }
  ignore_errors: true

- name: '< HA Service Set : DATABASE -04 > Debugging [ {{ vm_db_type | upper }} ]' 
  debug:
    msg: '{{ rs_ip_set_vm }}'
