---
- name: '< MAIN : WEB > [ {{ vm_purpose|upper }} ] Launch Create VM WEB Service HA Template'
  include_tasks: web_template.yml
  when: vm_web_ck == 'yes'

- name: '< MAIN : WAS > [ {{ vm_purpose|upper }} ] Launch Create VM WAS Service HA Template'
  include_tasks: was_template.yml

- name: '< MAIN : Database > [ {{ vm_purpose|upper }} ] Launch Create VM Database Service HA Template [ {{ vm_db_type|upper }} ]'
  include_tasks: database_template.yml
