---
- name: '< HA Service Set : WEB -01 > Creating a web service virtual machine'
  vmware_guest:
    validate_certs: false
    folder: /IAAS_Datacenter/vm
    datacenter: IAAS_Datacenter
    cluster: 'IAAS_iac(D)_Cluster'
    name: '{{ item }}'
    state: poweredon
    template: 'TMP_RHEL8.6_{{ vm_purpose|upper }}_WEB'
    disk:
    - size_gb: 60
      type: thin
      datastore: DIAAS_OS_NAS11
    - size_gb: 50
      type: thin
      datastore: DIAAS_OS_NAS11
    hardware:
      memory_mb: 4096
      num_cpus: 2
      scsi: paravirtual
      mem_reservation: 4096
      cpu_shares_level: "normal"
      mem_shares_level: "normal"
  delegate_to: localhost
  register: rs_create_vm
  loop:
    - '{{ vm_purpose[0:1] | lower }}{{ vm_code | lower }}web1v'
    - '{{ vm_purpose[0:1] | lower }}{{ vm_code | lower }}web2v'

- name: '< HA Service Set : WEB -01 > Debugging' 
  debug:
    msg: '{{ rs_create_vm }}'

- name: '< HA Service Set : WEB -02 > Web Service virtual machine booting stand by 30 second'
  pause:
    seconds: 30
    
- name: '< HA Service Set : WEB -03 > Web service virtual machine IP settings'
  vmware_vm_shell:
    validate_certs: false
    folder: /IAAS_Datacenter/vm
    datacenter: IAAS_Datacenter
    vm_id: '{{ item.hostname }}'
    vm_username: '{{ vm_user }}'
    vm_password: '{{ vm_pw }}'
    vm_shell: "/usr/bin/sudo"
    vm_shell_args: "nmcli con add con-name ens192 ifname ens192 type ethernet ip4 {{ item.ip_addr }}/24 ipv4.method manual autoconnect yes && sudo hostnamectl set-hostname {{ item.hostname }}"
  delegate_to: localhost
  register: rs_ip_set_vm
  loop:
    - { 'hostname':'{{ vm_purpose[0:1] | lower }}{{ vm_code | lower }}web1v', 'ip_addr':'{{ vm_ipaddr_1 }}' }
    - { 'hostname':'{{ vm_purpose[0:1] | lower }}{{ vm_code | lower }}web2v', 'ip_addr':'{{ vm_ipaddr_2 }}' }
  ignore_errors: true

- name: '< HA Service Set : WEB -03 > Debugging' 
  debug:
    msg: '{{ rs_ip_set_vm }}'
