---
- name: '< Haproxy {{ proxy_type|upper }} Setting - 01 > {{ proxy_type|upper }} Config Template Copy'
  shell: 'cp /engn/haproxy/conf/haproxy.{{ proxy_type|lower }}.cfg /etc/haproxy/haproxy.cfg'
  register: result_01

- name: '< Haproxy {{ proxy_type|upper }} Setting - 01 > Result Check'
  debug:
    msg: '{{ result_01 }}'
    
- name: '< Haproxy {{ proxy_type|upper }} Setting - 02 > {{ proxy_type|upper }} Config Bind Port'
  lineinfile:
    path: '/etc/haproxy/haproxy.cfg'
    regexp: '   bind :8888'
    line: '   bind :{{ bind_port }}'
  register: result_02

- name: '< Haproxy {{ proxy_type|upper }} Setting - 02 > Result Check'
  debug:
    msg: "'{{ result_02 }}'
    
- name: '"< Haproxy {{ proxy_type|upper }} Setting - 03 > Initialize the {{ proxy_type|upper }} Server member'
  lineinfile:
    path: '/etc/haproxy/haproxy.cfg'
    regexp: '{{ item }}'
    state: absent
  register: result_03
  loop:
    - 'server s1 192.168.1.25:8888 check fall 5 inter 2000 rise 2'
    - 'server s2 192.168.1.26:8888 check fall 5 inter 2000 rise 2'

- name: '< Haproxy {{ proxy_type|upper }} Setting - 03 > Result Check'
  debug:
    msg: '{{ result_03 }}'
    
- name: '< Haproxy {{ proxy_type|upper }} Setting - 04 > Add {{ proxy_type|upper }} server member'
  lineinfile:
    path: '/etc/haproxy/haproxy.cfg'
    insertafter: 'balance roundrobin'
    line: '{{ item }}'
  register: result_04
  loop:
    - '   server s2 {{ vm_member_2 }}:{{ bind_port }} check fall 5 inter 2000 rise 2'
    - '   server s1 {{ vm_member_1 }}:{{ bind_port }} check fall 5 inter 2000 rise 2'

- name: '< Haproxy {{ proxy_type|upper }} Setting - 04 > Result Check'
  debug:
    msg: '{{ result_04 }}'

- name: '< Haproxy {{ proxy_type|upper }} Setting - 05 > Running Haproxy'
  systemd:
    name: haproxy
    state: started
    enabled: true
  register: result_05

- name: '< Haproxy {{ proxy_type|upper }} Setting - 05 > Result Check'
  debug:
    msg: '{{ result_05 }}'

- name: '< Haproxy {{ proxy_type|upper }} Setting - 06 > modify Haproxy-exporter CLI'
  lineinfile:
    path: '/engn/haproxy/haproxy-prom-exporter.sh'
    regexp: '--haproxy.scrape-uri="http://1.1.1.10:11936/stats;csv"'
    line: '--haproxy.scrape-uri="http://{{ item }}/stats;csv"'
  register: result_06
  loop:
    - '{{ vm_ipaddr_1 }}'
    - '{{ vm_ipaddr_2 }}'
  when: inventory_hostname == item

- name: '< Haproxy {{ proxy_type|upper }} Setting - 06 > Result Check'
  debug:
    msg: '{{ result_06 }}'

- name: '< Haproxy {{ proxy_type|upper }} Setting - 07 > Running Container Haproxy-exporter'
  shell: 'sh /engn/haproxy/haproxy-prom-exporter.sh'
  register: result_07

- name: '< Haproxy {{ proxy_type|upper }} Setting - 07 > Result Check'
  debug:
    msg: '{{ result_07 }}'
