---
- name: '< haproxy Setting - 01 > Setting keepalived Config vrrp_instance state'
  lineinfile:
    path: '/etc/keepalived/keepalived.conf'
    regexp: 'state MASTER'
    line: '   state BACKUP'
  register: keep_result_01
  when: inventory_hostname == vm_ipaddr_2

- name: '< haproxy Setting - 01 > Result Check'
  debug:
    msg: '{{ keep_result_01 }}'
  when: inventory_hostname == vm_ipaddr_2

- name: '< haproxy Setting - 02 > Setting keepalived Variable VIP Ip address'
  set_fact:
    vip_split: '{{ vm_proxy_vip.split(".") }}'

- name: '< haproxy Setting - 03 > Setting keepalived Config vrrp_instance virtual_router_id'
  lineinfile:
    path: '/etc/keepalived/keepalived.conf'
    regexp: 'virtual_router_id 10'
    line: '   virtual_router_id {{ vip_split[3] }}'
  register: keep_result_02

- name: '< haproxy Setting - 03 > Result Check'
  debug:
    msg: '{{ keep_result_02 }}'

- name: '< haproxy Setting - 04 > Setting keepalived Config vrrp_instance virtual_ipadderss'
  lineinfile:
    path: '/etc/keepalived/keepalived.conf'
    regexp: '1.1.1.10'
    line: '      {{ vm_proxy_vip }}'
  register: keep_result_03

- name: '< haproxy Setting - 04 > Result Check'
  debug:
    msg: '{{ keep_result_03 }}'

- name: '< haproxy Setting - 05 > Running Keepalived'
  systemd:
    name: keepalived
    state: restarted
    enabled: true
  register: keep_result_04

- name: '< haproxy Setting - 05 > Result Check'
  debug:
    msg: '{{ keep_result_04 }}'
