---
- name: "Haproxy Config TCP or Proxy Setting"
  include_tasks: haproxy_tcp_config.yml
  when: (vm_type|lower == 'hpxy' and proxy_type|lower == 'tcp') or (vm_type|lower == 'hpxy' and proxy_type|lower == 'proxy')

- name: "Haproxy Config WEB Setting"
  include_tasks: haproxy_web_config.yml
  when: (vm_type|lower == 'hpxy' and proxy_type|lower == 'web')
