---
- name: 'New Create a virtual machine from a template ( VM Type is "Not OTHER" )'
  vmware_guest:
    validate_certs: false
    folder: /IAAS_Datacenter/vm
    datacenter: IAAS_Datacenter
    cluster: 'IAAS_iac(D)_Cluster'
    name: '{{ vm_purpose[0:1] | lower }}{{ vm_code | lower }}{{ vm_type | lower }}{{ item }}v'
    state: poweredon
    template: 'TMP_RHEL8.6_DEV_{{ vm_type | upper }}'
    disk:
    - size_gb: 60
      type: thin
      datastore: DIAAS_OS_NAS11
    - size_gb: 50
      type: thin
      datastore: DIAAS_OS_NAS11
    hardware:
      memory_mb: 4096
      num_cpus: 2
      scsi: paravirtual
      mem_reservation: 4096
      cpu_shares_level: "normal"
      mem_shares_level: "normal"
  delegate_to: localhost
  register: deploy
  with_sequence: start=1 end={{ vm_count }}
  when: vm_type|lower == 'pxy' or vm_type|lower == 'web' or vm_type|lower == 'was'

- name: debugging 
  debug:
    msg: '{{ deploy }}'
  when: vm_type|lower == 'pxy' or vm_type|lower == 'web' or vm_type|lower == 'was'

- name: 'New Create a virtual machine IP Setting ( VM Type is "Not OTHER" )'
  vmware_vm_shell:
    validate_certs: false
    folder: /IAAS_Datacenter/vm
    datacenter: IAAS_Datacenter
    vm_id: '{{ vm_purpose[0:1] | lower }}{{ vm_code | lower }}{{ vm_type | lower }}{{ item }}v'
    vm_username: 'iacusr'
    vm_password: '{{ vm_pw }}'
    vm_shell: "/usr/bin/sudo"
    vm_shell_args: "nmcli con mod ens192 ipv4.address {{ ip_addr }}/24 ipv4.method manual connection.autoconnect yes"
  delegate_to: localhost
  register: ip_result
  with_sequence: start=1 end={{ vm_count }}
  when: vm_type|lower == 'pxy' or vm_type|lower == 'web' or vm_type|lower == 'was'
  ignore_errors: true

- name: 'New Create a virtual machine from a template ( VM Type is "Not OTHER and HAPROXY" )'
  vmware_guest:
    validate_certs: false
    folder: /IAAS_Datacenter/vm
    datacenter: IAAS_Datacenter
    cluster: 'IAAS_iac(D)_Cluster'
    name: '{{ vm_purpose[0:1] | lower }}{{ vm_code | lower }}pxy{{ item }}v'
    state: poweredon
    template: 'TMP_RHEL8.6_DEV_{{ vm_type | upper }}'
    disk:
    - size_gb: 60
      type: thin
      datastore: DIAAS_OS_NAS11
    - size_gb: 50
      type: thin
      datastore: DIAAS_OS_NAS11
    hardware:
      memory_mb: 4096
      num_cpus: 2
      scsi: paravirtual
      mem_reservation: 4096
      cpu_shares_level: "normal"
      mem_shares_level: "normal"
  delegate_to: localhost
  register: deploy
  with_sequence: start=1 end={{ vm_count }}
  when: vm_type|lower == 'hpxy'

- name: debugging 
  debug:
    msg: '{{ deploy }}'
  when: vm_type|lower == 'hpxy'

- name: 'New Create a virtual machine IP Setting ( VM Type is "Not OTHER and HAPROXY" )'
  vmware_vm_shell:
    validate_certs: false
    folder: /IAAS_Datacenter/vm
    datacenter: IAAS_Datacenter
    vm_id: '{{ vm_purpose[0:1] | lower }}{{ vm_code | lower }}pxy{{ item }}v'
    vm_username: 'iacusr'
    vm_password: '{{ vm_pw }}'
    vm_shell: "/usr/bin/sudo"
    vm_shell_args: "nmcli con mod ens192 ipv4.address {{ ip_addr }}/24 ipv4.method manual connection.autoconnect yes"
  delegate_to: localhost
  register: ip_result
  with_sequence: start=1 end={{ vm_count }}
  when: vm_type|lower == 'hpxy'
  ignore_errors: true

- name: 'New Create a virtual machine from a template ( VM Type is "Not OTHER and Database Mysql or MariaDB" )'
  vmware_guest:
    validate_certs: false
    folder: /IAAS_Datacenter/vm
    datacenter: IAAS_Datacenter
    cluster: 'IAAS_iac(D)_Cluster'
    name: '{{ vm_purpose[0:1] | lower }}{{ vm_code | lower }}{{ vm_type | lower }}{{ item }}v'
    state: poweredon
    template: 'TMP_RHEL8.6_DEV_{{ vm_type | upper }}'
    disk:
    - size_gb: 60
      type: thin
      datastore: DIAAS_OS_NAS11
    - size_gb: 370
      type: thin
      datastore: DIAAS_OS_NAS11
    hardware:
      memory_mb: 4096
      num_cpus: 2
      scsi: paravirtual
      mem_reservation: 4096
      cpu_shares_level: "normal"
      mem_shares_level: "normal"
  delegate_to: localhost
  register: deploy
  with_sequence: start=1 end={{ vm_count }}
  when: vm_type|lower == 'mas' or vm_type|lower == 'mys'

- name: debugging 
  debug:
    msg: '{{ deploy }}'
  when: vm_type|lower == 'mas' or vm_type|lower == 'mys'

- name: 'New Create a virtual machine from a template ( VM TYPE is "OTHER" )'
  vmware_guest:
    validate_certs: false
    folder: /IAAS_Datacenter/vm
    datacenter: IAAS_Datacenter
    cluster: 'IAAS_iac(D)_Cluster'
    name: '{{ vm_purpose[0:1] | lower }}{{ vm_code | lower }}{{ vm_type | lower }}{{ item }}v'
    state: poweredon
    template: 'TMP_RHEL8.6_60_50_DEV'
    disk:
    - size_gb: 60
      type: thin
      datastore: DIAAS_OS_NAS11
    - size_gb: 50
      type: thin
      datastore: DIAAS_OS_NAS11
    hardware:
      memory_mb: 4096
      num_cpus: 2
      scsi: paravirtual
      mem_reservation: 4096
      cpu_shares_level: "normal"
      mem_shares_level: "normal"
  delegate_to: localhost
  register: deploy
  with_sequence: start=1 end={{ vm_count }}
  when: vm_type|lower != 'pxy' and vm_type|lower != 'web' and vm_type|lower != 'was' and vm_type|lower != 'mas' and vm_type|lower != 'mys' and vm_type|lower != 'hpxy'

- name: debugging 
  debug:
    msg: '{{ deploy }}'
  when: vm_type|lower != 'pxy' and vm_type|lower != 'web' and vm_type|lower != 'was' and vm_type|lower != 'mas' and vm_type|lower != 'mys' and vm_type|lower != 'hpxy'
  
