---
# Log -01 : 시스템 하드웨어 fault 로그 확인
- name: '< Check : Log -01 > Messages Log [ Fault | Error | Fail ]'
  shell: 'cat /var/log/messages | egrep -iv "default|ansible" | grep -E "fault|error|fail" | head -3'
  register: get_logs
  ignore_errors: true

# 상기 수집된 정보를 CSV File로 출력하기 위해 전역 변수에 저장.
# 수집 결과 저장시 이상 유무 조건을 체크하여 저장 처리
- name: '< Check -01 > Set Result'
  set_fact:
    rs_logs: '{{ "OK" if( get_logs.rc == 0 ) else get_logs.stdout }}'
